modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
issueTrackerURL="https://github.com/Andromander/Gaia-Dimension/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="gaiadimension" #mandatory
version="1.1.0" #mandatory
displayName="The Gaia Dimension" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Andromander/Gaia-Dimension/master/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/gaia-dimension" #optional
#logoFile="" #optional
credits="Androsa, and the Gaia Dimension contributors." #optional
authors="Androsa" #optional
description="Explore the fantastical land of Gaia and uncover the secrets within."

[[dependencies.gaiadimension]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.gaiadimension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"