modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
issueTrackerURL="https://github.com/Andromander/Gaia-Dimension/issues" #optional
license="GNU Lesser General Public v3"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="gaiadimension" #mandatory
version="${mod_version}" #mandatory
displayName="The Gaia Dimension" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Andromander/Gaia-Dimension/1.20.x/update.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/gaia-dimension" #optional
#logoFile="" #optional
credits="Androsa, and the Gaia Dimension contributors." #optional
authors="Androsa" #optional
description="Explore the fantastical land of Gaia and uncover the secrets within."
enumExtensions="META-INF/enumextensions.json"

[[dependencies.gaiadimension]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neoforge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.gaiadimension]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"