name: Bug Report (Beta)
description: Create an issue about a potential bug
title: ''
labels: [bug]
body:
  - type: input
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running?
      placeholder: "Example: 1.16.5"
    validations:
      required: true
  - type: input
    attributes:
      label: Forge Version
      description: What version of Forge are you using? This can be found on the jar file you downloaded from the Forge website or the installation setting.
      placeholder: "Example: 36.1.0"
    validations:
      required: true
  - type: input
    attributes:
      label: Gaia Dimension Version
      description: What version of Gaia Dimension are you using? This can be found on the jar file you downloaded from Curseforge or the repository.
      placeholder: "Example: 1.3.2"
    validations:
      required: true
  - type: input
    attributes:
      label: Client Log
      description: A [Gist](https://gist.github.com/) link to the client log of when the issue happened. Provide the full log.
  - type: textarea
    attributes:
      label: To Reproduce
      description: Describe to the best of your ability how you encountered this bug if it isn't immediately obvious.
      value: |
        1. First step
        2. Second step
        3. Third and so on...more steps can be added
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what happened. Be as detailed as possible, including what you think should have happened.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Details
      description: Include any additional info that will help diagnose the bug. You can include video or screenshot evidence, details about other mods that may be involved, or links to issues in other repositories.
  - type: checkboxes
    attributes:
      label: Please read and confirm you have done the following
      options:
        - label: I have verified my report is unique and is not already opened or closed.
          required: true
        - label : The versions listed above are accurate and not a vague answer (ie. "Latest", "I don't know") and all details provided are clear and concise.
          required: true