package androsa.gaiadimension.registry;

import androsa.gaiadimension.GaiaDimension;
import androsa.gaiadimension.biomes.*;
import net.minecraft.world.biome.Biome;
import net.minecraftforge.registries.ObjectHolder;

@ObjectHolder(GaiaDimension.MODID)
public class ModBiomes {
    public static final Biome pink_agate_forest = new PinkAgateForestBiome((new Biome.Builder())
            .surfaceBuilder(ModWorldgen.DEFAULT_GAIA, ModWorldgen.GENERIC_SURFACE_CONFIG)
            .precipitation(Biome.RainType.NONE)
            .category(Biome.Category.FOREST)
            .depth(0.1F)
            .scale(0.1F)
            .temperature(0.66F)
            .downfall(0.0F)
            .waterColor(0x6C99B1)
            .waterFogColor(0x92BED4)
            .parent(null));
    public static final Biome blue_agate_taiga = new BlueAgateTaigaBiome((new Biome.Builder())
            .surfaceBuilder(ModWorldgen.DEFAULT_GAIA, ModWorldgen.GENERIC_SURFACE_CONFIG)
            .precipitation(Biome.RainType.NONE)
            .category(Biome.Category.TAIGA)
            .depth(0.1F)
            .scale(0.2F)
            .temperature(0.4F)
            .downfall(0.0F)
            .waterColor(0x6C99B1)
            .waterFogColor(0x92BED4)
            .parent(null));
    public static final Biome green_agate_jungle = new GreenAgateJungleBiome((new Biome.Builder())
            .surfaceBuilder(ModWorldgen.DEFAULT_GAIA, ModWorldgen.GENERIC_SURFACE_CONFIG)
            .precipitation(Biome.RainType.NONE)
            .category(Biome.Category.JUNGLE)
            .depth(0.1F)
            .scale(0.2F)
            .temperature(0.75F)
            .downfall(0.0F)
            .waterColor(0x6C99B1)
            .waterFogColor(0x92BED4)
            .parent(null));
    public static final Biome purple_agate_swamp = new PurpleAgateSwampBiome((new Biome.Builder())
            .surfaceBuilder(ModWorldgen.DEFAULT_GAIA, ModWorldgen.GENERIC_SURFACE_CONFIG)
            .precipitation(Biome.RainType.NONE)
            .category(Biome.Category.SWAMP)
            .depth(0.0F)
            .scale(0.05F)
            .temperature(0.66F)
            .downfall(0.0F)
            .waterColor(0x6C99B1)
            .waterFogColor(0x92BED4)
            .parent(null));
    public static final Biome fossil_woodland = new FossilWoodlandBiome((new Biome.Builder())
            .surfaceBuilder(ModWorldgen.DEFAULT_GAIA, ModWorldgen.GENERIC_SURFACE_CONFIG)
            .precipitation(Biome.RainType.NONE)
            .category(Biome.Category.FOREST)
            .depth(0.1F)
            .scale(0.05F)
            .temperature(0.66F)
            .downfall(0.0F)
            .waterColor(0x6C99B1)
            .waterFogColor(0x92BED4)
            .parent(null));
    public static final Biome mutant_agate_wildwood = new MutantAgateWildwoodBiome((new Biome.Builder())
            .surfaceBuilder(ModWorldgen.DEFAULT_GAIA, ModWorldgen.GENERIC_SURFACE_CONFIG)
            .precipitation(Biome.RainType.NONE)
            .category(Biome.Category.FOREST)
            .depth(0.1F)
            .scale(0.1F)
            .temperature(0.66F)
            .downfall(0.0F)
            .waterColor(0x6C99B1)
            .waterFogColor(0x92BED4)
            .parent(null));
    public static final Biome volcaniclands = new VolcaniclandsBiome((new Biome.Builder())
            .surfaceBuilder(ModWorldgen.VOLCANIC, ModWorldgen.VOLCANIC_SURFACE_CONFIG)
            .precipitation(Biome.RainType.NONE)
            .category(Biome.Category.EXTREME_HILLS)
            .depth(1.0F)
            .scale(0.7F)
            .temperature(0.9F)
            .downfall(0.0F)
            .waterColor(0x6C99B1)
            .waterFogColor(0x92BED4)
            .parent(null));
    public static final Biome static_wasteland = new StaticWastelandBiome((new Biome.Builder())
            .surfaceBuilder(ModWorldgen.WASTELAND, ModWorldgen.WASTELAND_SURFACE_CONFIG)
            .precipitation(Biome.RainType.NONE)
            .category(Biome.Category.EXTREME_HILLS)
            .depth(3.0F)
            .scale(0.05F)
            .temperature(0.4F)
            .downfall(0.0F)
            .waterColor(0x6C99B1)
            .waterFogColor(0x92BED4)
            .parent(null));
    public static final Biome goldstonelands = new GoldstonelandsBiome((new Biome.Builder())
            .surfaceBuilder(ModWorldgen.DEFAULT_GAIA, ModWorldgen.CORRUPT_SURFACE_CONFIG)
            .precipitation(Biome.RainType.NONE)
            .category(Biome.Category.PLAINS)
            .depth(0.125F)
            .scale(0.05F)
            .temperature(0.55F)
            .downfall(0.0F)
            .waterColor(0x6C99B1)
            .waterFogColor(0x92BED4)
            .parent(null));
    public static final Biome crystal_plains = new CrystalPlainsBiome((new Biome.Builder())
            .surfaceBuilder(ModWorldgen.DEFAULT_GAIA, ModWorldgen.GENERIC_SURFACE_CONFIG)
            .precipitation(Biome.RainType.NONE)
            .category(Biome.Category.PLAINS)
            .depth(0.05F)
            .scale(0.05F)
            .temperature(0.66F)
            .downfall(0.0F)
            .waterColor(0x6C99B1)
            .waterFogColor(0x92BED4)
            .parent(null));
    public static final Biome salt_dunes = new SaltDunesBiome((new Biome.Builder())
            .surfaceBuilder(ModWorldgen.DEFAULT_GAIA, ModWorldgen.SALT_SURFACE_CONFIG)
            .precipitation(Biome.RainType.NONE)
            .category(Biome.Category.DESERT)
            .depth(0.2F)
            .scale(0.05F)
            .temperature(0.8F)
            .downfall(0.0F)
            .waterColor(0x6C99B1)
            .waterFogColor(0x92BED4)
            .parent(null));
    public static final Biome shining_grove = new ShiningGroveBiome((new Biome.Builder())
            .surfaceBuilder(ModWorldgen.DEFAULT_GAIA, ModWorldgen.AURA_SURFACE_CONFIG)
            .precipitation(Biome.RainType.NONE)
            .category(Biome.Category.FOREST)
            .depth(0.4F)
            .scale(0.05F)
            .temperature(0.5F)
            .downfall(0.0F)
            .waterColor(0x6C99B1)
            .waterFogColor(0x92BED4)
            .parent(null));
    public static final Biome smoldering_bog = new SmolderingBogBiome((new Biome.Builder())
            .surfaceBuilder(ModWorldgen.DEFAULT_GAIA, ModWorldgen.BISMUTH_SURFACE_CONFIG)
            .precipitation(Biome.RainType.NONE)
            .category(Biome.Category.SWAMP)
            .depth(0.2F)
            .scale(0.02F)
            .temperature(0.9F)
            .downfall(0.0F)
            .waterColor(0x6C99B1)
            .waterFogColor(0x92BED4)
            .parent(null));
    public static final Biome mineral_reservoir = new MineralReservoirBiome((new Biome.Builder())
            .surfaceBuilder(ModWorldgen.DEFAULT_GAIA, ModWorldgen.SALT_SURFACE_CONFIG)
            .precipitation(Biome.RainType.NONE)
            .category(Biome.Category.OCEAN)
            .depth(-1.8F)
            .scale(0.1F)
            .temperature(0.66F)
            .downfall(0.0F)
            .waterColor(0x6C99B1)
            .waterFogColor(0x92BED4)
            .parent(null));
    public static final Biome mineral_river = new MineralRiverBiome((new Biome.Builder())
            .surfaceBuilder(ModWorldgen.DEFAULT_GAIA, ModWorldgen.SALT_SURFACE_CONFIG)
            .precipitation(Biome.RainType.NONE)
            .category(Biome.Category.OCEAN)
            .depth(-0.5F)
            .scale(0.0F)
            .temperature(0.66F)
            .downfall(0.0F)
            .waterColor(0x6C99B1)
            .waterFogColor(0x92BED4)
            .parent(null));
}
