package androsa.gaiadimension.registry;

import androsa.gaiadimension.GaiaDimensionMod;
import androsa.gaiadimension.item.*;
import androsa.gaiadimension.item.armor.*;
import androsa.gaiadimension.item.tools.*;
import net.minecraft.block.Block;
import net.minecraft.fluid.Fluids;
import net.minecraft.item.*;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.IForgeRegistry;
import net.minecraftforge.registries.ObjectHolder;

import static net.minecraft.inventory.EquipmentSlotType.*;

@ObjectHolder(GaiaDimensionMod.MODID)
@Mod.EventBusSubscriber(modid = GaiaDimensionMod.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class ModItems {

    public static final Item crystallized_redstone = new BasicGaiaItem();
    public static final Item crystallized_lapis_lazuli = new BasicGaiaItem();
    public static final Item glint_and_gold = new GlintAndGoldItem();
    public static final Item agate_stick = new BasicGaiaItem();
    public static final Item hot_dust = new BasicGaiaItem() {
        @Override
        public int getBurnTime(ItemStack stack) {
            return 100;
        }
    };
    public static final Item goldstone_dust = new BasicGaiaItem();
    public static final Item fine_dust = new BasicGaiaItem();
    public static final Item cloudy_shard = new BasicGaiaItem();
    public static final Item agate_cup = new BasicGaiaItem();
    public static final Item scaynyx_ingot = new BasicGaiaItem();
    public static final Item sweet_muckball = new BasicGaiaItem();
    public static final Item sugar_crystals = new BasicGaiaItem();
    public static final Item sugar_cluster = new BasicGaiaItem();
    public static final Item shiny_bone = new BasicGaiaItem();
    public static final Item fine_thread = new BasicGaiaItem();
    public static final Item twined_thread = new BasicGaiaItem();
    public static final Item pink_essence = new BasicGaiaItem();
    public static final Item pink_goo = new BasicGaiaItem();
    public static final Item gemstone_pouch = new GemstonePouchItem();
    public static final Item agate_fabric = new BasicGaiaItem();
    public static final Item sturdy_pebble = new SturdyPebbleItem();
    public static final Item scaynyx_bucket = new ScaynyxBucketItem(Fluids.EMPTY);
    public static final Item mineral_water_bucket = new ScaynyxBucketItem(ModFluids.mineral_water_still);
    public static final Item superhot_magma_bucket = new ScaynyxBucketItem(ModFluids.superhot_magma_still);
    public static final Item sweet_muck_bucket = new ScaynyxBucketItem(ModFluids.sweet_muck_still);
    public static final Item liquid_bismuth_bucket = new ScaynyxBucketItem(ModFluids.liquid_bismuth_still);
    public static final Item liquid_aura_bucket = new ScaynyxBucketItem(ModFluids.liquid_aura_still);

    public static final Item pink_geode = new BasicGaiaItem();
    public static final Item blue_geode = new BasicGaiaItem();
    public static final Item green_geode = new BasicGaiaItem();
    public static final Item purple_geode = new BasicGaiaItem();
    public static final Item pink_geode_slice = new GeodeSliceItem(GaiaFoods.PINK_SLICE);
    public static final Item blue_geode_slice = new GeodeSliceItem(GaiaFoods.BLUE_SLICE);
    public static final Item green_geode_slice = new GeodeSliceItem(GaiaFoods.GREEN_SLICE);
    public static final Item purple_geode_slice = new GeodeSliceItem(GaiaFoods.PURPLE_SLICE);
    public static final Item pink_geode_juice = new GeodeJuiceItem(GaiaFoods.PINK_JUICE);
    public static final Item blue_geode_tea = new GeodeJuiceItem(GaiaFoods.BLUE_TEA);
    public static final Item green_geode_ale = new GeodeJuiceItem(GaiaFoods.GREEN_ALE);
    public static final Item purple_geode_soda = new GeodeJuiceItem(GaiaFoods.PURPLE_SODA);
    public static final Item pearly_geode_elixir = new GeodeJuiceItem(GaiaFoods.PEARLY_ELIXIR);
    public static final Item lurmorus_meat = new BasicGaiaItem(GaiaFoods.LURMORUS_MEAT);
    public static final Item lurmorus_steak = new BasicGaiaItem(GaiaFoods.LURMORUS_STEAK);
    public static final Item small_tentacle = new BasicGaiaItem(GaiaFoods.SMALL_TENTACLE);
    public static final Item small_calamari = new BasicGaiaItem(GaiaFoods.SMALL_CALAMARI);
    public static final Item large_tentacle = new BasicGaiaItem(GaiaFoods.LARGE_TENTACLE);
    public static final Item large_calamari = new BasicGaiaItem(GaiaFoods.LARGE_CALAMARI);
    public static final Item markuzar_mint = new BasicGaiaItem(GaiaFoods.MARKUZAR_MINT);
    public static final Item luggeroth_chop = new BasicGaiaItem(GaiaFoods.LUGGEROTH_CHOP);
    public static final Item cooked_luggeroth_chop = new BasicGaiaItem(GaiaFoods.COOKED_LUGGEROTH_CHOP);
    public static final Item tilipi = new BasicGaiaItem(GaiaFoods.TILIPI);
    public static final Item tilibl = new BasicGaiaItem(GaiaFoods.TILIBL);
    public static final Item tiligr = new BasicGaiaItem(GaiaFoods.TILIGR);
    public static final Item tilipu = new BasicGaiaItem(GaiaFoods.TILIPU);
    public static final Item tiliol = new BasicGaiaItem(GaiaFoods.TILIOL);
    public static final Item tilimy = new BasicGaiaItem(GaiaFoods.TILIMY);
    public static final Item plagued_tiliey = new BasicGaiaItem(GaiaFoods.PLAGUED_TILIEY);
    public static final Item tiliou = new BasicGaiaItem(GaiaFoods.TILIOU);

    public static final Item hematite_powder = new GroundGemItem();
    public static final Item pyrite_powder = new GroundGemItem();
    public static final Item labradorite_powder = new GroundGemItem();
    public static final Item moonstone_powder = new GroundGemItem();
    public static final Item cinnabar_powder = new GroundGemItem();
    public static final Item red_opal_powder = new GroundGemItem();
    public static final Item blue_opal_powder = new GroundGemItem();
    public static final Item green_opal_powder = new GroundGemItem();
    public static final Item white_opal_grit = new GroundGemItem();

    public static final Item sugilite = new BasicGaiaItem();
    public static final Item hematite = new BasicGaiaItem();
    public static final Item pyrite = new BasicGaiaItem();
    public static final Item labradorite = new BasicGaiaItem();
    public static final Item moonstone = new BasicGaiaItem();
    public static final Item cinnabar = new BasicGaiaItem();
    public static final Item red_opal = new BasicGaiaItem();
    public static final Item blue_opal = new BasicGaiaItem();
    public static final Item green_opal = new BasicGaiaItem();
    public static final Item white_opal = new BasicGaiaItem();
    public static final Item ixiolite = new BasicGaiaItem();
    public static final Item proustite = new BasicGaiaItem();
    public static final Item euclase = new BasicGaiaItem();
    public static final Item leucite = new BasicGaiaItem();
    public static final Item carnelian = new BasicGaiaItem();
    public static final Item benitoite = new BasicGaiaItem();
    public static final Item diopside = new BasicGaiaItem();
    public static final Item chalcedony = new BasicGaiaItem();
    public static final Item black_residue = new BasicGaiaItem();
    public static final Item tektite = new BasicGaiaItem();
    public static final Item goldstone = new BasicGaiaItem();
    public static final Item goldstone_residue = new BasicGaiaItem();
    public static final Item aura_residue = new BasicGaiaItem();
    public static final Item aura_cluster = new BasicGaiaItem();
    public static final Item bismuth_residue = new BasicGaiaItem();
    public static final Item bismuth_crystal = new BasicGaiaItem();

    public static final Item sugilite_helmet = new BasicGaiaArmorItem(GaiaArmorMaterials.SUGILITE, HEAD);
    public static final Item sugilite_chestplate = new BasicGaiaArmorItem(GaiaArmorMaterials.SUGILITE, CHEST);
    public static final Item sugilite_legs = new BasicGaiaArmorItem(GaiaArmorMaterials.SUGILITE, LEGS);
    public static final Item sugilite_boots = new BasicGaiaArmorItem(GaiaArmorMaterials.SUGILITE, FEET);
    public static final Item proustite_helmet = new BasicGaiaArmorItem(GaiaArmorMaterials.PROUSTITE, HEAD);
    public static final Item proustite_chestplate = new BasicGaiaArmorItem(GaiaArmorMaterials.PROUSTITE, CHEST);
    public static final Item proustite_legs = new BasicGaiaArmorItem(GaiaArmorMaterials.PROUSTITE, LEGS);
    public static final Item proustite_boots = new BasicGaiaArmorItem(GaiaArmorMaterials.PROUSTITE, FEET);
    public static final Item leucite_helmet = new BasicGaiaArmorItem(GaiaArmorMaterials.LEUCITE, HEAD);
    public static final Item leucite_chestplate = new BasicGaiaArmorItem(GaiaArmorMaterials.LEUCITE, CHEST);
    public static final Item leucite_legs = new BasicGaiaArmorItem(GaiaArmorMaterials.LEUCITE, LEGS);
    public static final Item leucite_boots = new BasicGaiaArmorItem(GaiaArmorMaterials.LEUCITE, FEET);
    public static final Item carnelian_helmet = new BasicGaiaArmorItem(GaiaArmorMaterials.CARNELIAN, HEAD);
    public static final Item carnelian_chestplate = new BasicGaiaArmorItem(GaiaArmorMaterials.CARNELIAN, CHEST);
    public static final Item carnelian_legs = new BasicGaiaArmorItem(GaiaArmorMaterials.CARNELIAN, LEGS);
    public static final Item carnelian_boots = new BasicGaiaArmorItem(GaiaArmorMaterials.CARNELIAN, FEET);
    public static final Item diopside_helmet = new BasicGaiaArmorItem(GaiaArmorMaterials.DIOPSIDE, HEAD);
    public static final Item diopside_chestplate = new BasicGaiaArmorItem(GaiaArmorMaterials.DIOPSIDE, CHEST);
    public static final Item diopside_legs = new BasicGaiaArmorItem(GaiaArmorMaterials.DIOPSIDE, LEGS);
    public static final Item diopside_boots = new BasicGaiaArmorItem(GaiaArmorMaterials.DIOPSIDE, FEET);
    public static final Item chalcedony_helmet = new BasicGaiaArmorItem(GaiaArmorMaterials.CHALCEDONY, HEAD);
    public static final Item chalcedony_chestplate = new BasicGaiaArmorItem(GaiaArmorMaterials.CHALCEDONY, CHEST);
    public static final Item chalcedony_legs = new BasicGaiaArmorItem(GaiaArmorMaterials.CHALCEDONY, LEGS);
    public static final Item chalcedony_boots = new BasicGaiaArmorItem(GaiaArmorMaterials.CHALCEDONY, FEET);

    public static final Item malachite_guard_headgear = new MalachiteGuardArmorItem(GaiaArmorMaterials.MALACHITE, HEAD);
    public static final Item malachite_guard_brace = new MalachiteGuardArmorItem(GaiaArmorMaterials.MALACHITE, CHEST);
    public static final Item malachite_guard_gear = new MalachiteGuardArmorItem(GaiaArmorMaterials.MALACHITE, LEGS);
    public static final Item malachite_guard_boots = new MalachiteGuardArmorItem(GaiaArmorMaterials.MALACHITE, FEET);
    public static final Item apex_predator_hood = new ApexPredatorArmorItem(GaiaArmorMaterials.TIGER_EYE, HEAD);
    public static final Item apex_predator_jacket = new ApexPredatorArmorItem(GaiaArmorMaterials.TIGER_EYE, CHEST);
    public static final Item apex_predator_trousers = new ApexPredatorArmorItem(GaiaArmorMaterials.TIGER_EYE, LEGS);
    public static final Item apex_predator_boots = new ApexPredatorArmorItem(GaiaArmorMaterials.TIGER_EYE, FEET);
    public static final Item spinel_princess_cowl = new SpinelPrincessArmorItem(GaiaArmorMaterials.SPINEL, HEAD);
    public static final Item spinel_princess_cloak = new SpinelPrincessArmorItem(GaiaArmorMaterials.SPINEL, CHEST);
    public static final Item spinel_princess_dress = new SpinelPrincessArmorItem(GaiaArmorMaterials.SPINEL, LEGS);
    public static final Item spinel_princess_heels = new SpinelPrincessArmorItem(GaiaArmorMaterials.SPINEL, FEET);
    public static final Item zircon_prince_crown = new ZirconPrinceArmorItem(GaiaArmorMaterials.ZIRCON, HEAD);
    public static final Item zircon_prince_chestpiece = new ZirconPrinceArmorItem(GaiaArmorMaterials.ZIRCON, CHEST);
    public static final Item zircon_prince_gear = new ZirconPrinceArmorItem(GaiaArmorMaterials.ZIRCON, LEGS);
    public static final Item zircon_prince_boots = new ZirconPrinceArmorItem(GaiaArmorMaterials.ZIRCON, FEET);
    public static final Item corrupt_warrior_helm = new CorruptWarriorArmorItem(GaiaArmorMaterials.CORRUPT, HEAD);
    public static final Item corrupt_warrior_guard = new CorruptWarriorArmorItem(GaiaArmorMaterials.CORRUPT, CHEST);
    public static final Item corrupt_warrior_greaves = new CorruptWarriorArmorItem(GaiaArmorMaterials.CORRUPT, LEGS);
    public static final Item corrupt_warrior_boots = new CorruptWarriorArmorItem(GaiaArmorMaterials.CORRUPT, FEET);
    public static final Item gaia_duchess_helm = new GaiaDuchessArmorItem(GaiaArmorMaterials.BIXBITE, HEAD);
    public static final Item gaia_duchess_guard = new GaiaDuchessArmorItem(GaiaArmorMaterials.BIXBITE, CHEST);
    public static final Item gaia_duchess_greaves = new GaiaDuchessArmorItem(GaiaArmorMaterials.BIXBITE, LEGS);
    public static final Item gaia_duchess_boots = new GaiaDuchessArmorItem(GaiaArmorMaterials.BIXBITE, FEET);
    public static final Item gaia_baron_mask = new GaiaBaronArmorItem(GaiaArmorMaterials.TSAVORITE, HEAD);
    public static final Item gaia_baron_tuxedo = new GaiaBaronArmorItem(GaiaArmorMaterials.TSAVORITE, CHEST);
    public static final Item gaia_baron_pants = new GaiaBaronArmorItem(GaiaArmorMaterials.TSAVORITE, LEGS);
    public static final Item gaia_baron_shoes = new GaiaBaronArmorItem(GaiaArmorMaterials.TSAVORITE, FEET);
    public static final Item gaia_duke_helm = new GaiaDukeArmorItem(GaiaArmorMaterials.LARVIKITE, HEAD);
    public static final Item gaia_duke_guard = new GaiaDukeArmorItem(GaiaArmorMaterials.LARVIKITE, CHEST);
    public static final Item gaia_duke_greaves = new GaiaDukeArmorItem(GaiaArmorMaterials.LARVIKITE, LEGS);
    public static final Item gaia_duke_boots = new GaiaDukeArmorItem(GaiaArmorMaterials.LARVIKITE, FEET);
    public static final Item gaia_champion_helm = new GaiaChampArmorItem(GaiaArmorMaterials.GAIA_CHAMP, HEAD);
    public static final Item gaia_champion_guard = new GaiaChampArmorItem(GaiaArmorMaterials.GAIA_CHAMP, CHEST);
    public static final Item gaia_champion_greaves = new GaiaChampArmorItem(GaiaArmorMaterials.GAIA_CHAMP, LEGS);
    public static final Item gaia_champion_boots = new GaiaChampArmorItem(GaiaArmorMaterials.GAIA_CHAMP, FEET);

    public static final Item agate_sword = new BasicGaiaSwordItem(GaiaToolMaterials.AGATE);
    public static final Item agate_pickaxe = new BasicGaiaPickaxeItem(GaiaToolMaterials.AGATE);
    public static final Item agate_axe = new BasicGaiaAxeItem(GaiaToolMaterials.AGATE);
    public static final Item agate_shovel = new BasicGaiaShovelItem(GaiaToolMaterials.AGATE);
    public static final Item sugilite_sword = new BasicGaiaSwordItem(GaiaToolMaterials.SUGILITE);
    public static final Item sugilite_pickaxe = new BasicGaiaPickaxeItem(GaiaToolMaterials.SUGILITE);
    public static final Item sugilite_axe = new BasicGaiaAxeItem(GaiaToolMaterials.SUGILITE);
    public static final Item sugilite_shovel = new BasicGaiaShovelItem(GaiaToolMaterials.SUGILITE);
    public static final Item ixiolite_sword = new BasicGaiaSwordItem(GaiaToolMaterials.IXIOLITE);
    public static final Item ixiolite_pickaxe = new BasicGaiaPickaxeItem(GaiaToolMaterials.IXIOLITE);
    public static final Item ixiolite_axe = new BasicGaiaAxeItem(GaiaToolMaterials.IXIOLITE);
    public static final Item ixiolite_shovel = new BasicGaiaShovelItem(GaiaToolMaterials.IXIOLITE);
    public static final Item euclase_sword = new BasicGaiaSwordItem(GaiaToolMaterials.EUCLASE);
    public static final Item euclase_pickaxe = new BasicGaiaPickaxeItem(GaiaToolMaterials.EUCLASE);
    public static final Item euclase_axe = new BasicGaiaAxeItem(GaiaToolMaterials.EUCLASE);
    public static final Item euclase_shovel = new BasicGaiaShovelItem(GaiaToolMaterials.EUCLASE);
    public static final Item carnelian_sword = new BasicGaiaSwordItem(GaiaToolMaterials.CARNELIAN);
    public static final Item carnelian_pickaxe = new BasicGaiaPickaxeItem(GaiaToolMaterials.CARNELIAN);
    public static final Item carnelian_axe = new BasicGaiaAxeItem(GaiaToolMaterials.CARNELIAN);
    public static final Item carnelian_shovel = new BasicGaiaShovelItem(GaiaToolMaterials.CARNELIAN);
    public static final Item benitoite_sword = new BasicGaiaSwordItem(GaiaToolMaterials.BENITOITE);
    public static final Item benitoite_pickaxe = new BasicGaiaPickaxeItem(GaiaToolMaterials.BENITOITE);
    public static final Item benitoite_axe = new BasicGaiaAxeItem(GaiaToolMaterials.BENITOITE);
    public static final Item benitoite_shovel = new BasicGaiaShovelItem(GaiaToolMaterials.BENITOITE);
    public static final Item chalcedony_sword = new BasicGaiaSwordItem(GaiaToolMaterials.CHALCEDONY);
    public static final Item chalcedony_pickaxe = new BasicGaiaPickaxeItem(GaiaToolMaterials.CHALCEDONY);
    public static final Item chalcedony_axe = new BasicGaiaAxeItem(GaiaToolMaterials.CHALCEDONY);
    public static final Item chalcedony_shovel = new BasicGaiaShovelItem(GaiaToolMaterials.CHALCEDONY);
    public static final Item agate_arrow = new AgateArrowItem();
    public static final Item old_bow = new OldBowItem();

    public static final Item malachite_guard_baton = new MalachiteGuardSwordItem(GaiaToolMaterials.MALACHITE);
    public static final Item apex_predator_mace = new ApexPredatorSwordItem(GaiaToolMaterials.TIGER_EYE);
    public static final Item spinel_princess_flamberge = new SpinelPrincessSwordItem(GaiaToolMaterials.SPINEL);
    public static final Item zircon_prince_razor = new ZirconPrinceSwordItem(GaiaToolMaterials.ZIRCON);
    public static final Item corrupt_warrior_sword = new CorruptWarriorSwordItem(GaiaToolMaterials.CORRUPT);
    public static final Item gaia_duchess_khopesh = new GaiaDuchessSwordItem(GaiaToolMaterials.BIXBITE);
    public static final Item gaia_baron_dagger = new GaiaBaronSwordItem(GaiaToolMaterials.TSAVORITE);
    public static final Item gaia_duke_blade = new GaiaDukeSwordItem(GaiaToolMaterials.LARVIKITE);
    public static final Item gaia_champion_sword = new GaiaChampSwordItem(GaiaToolMaterials.GAIA_CHAMP);

    public static final Item growth_sapper_spawn_egg = new SpawnEggItem(ModEntities.GROWTH_SAPPER, 0x5A4514, 0xFF00FF, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item mutant_growth_extractor_spawn_egg = new SpawnEggItem(ModEntities.MUTANT_GROWTH_EXTRACTOR, 0x5A4514, 0xFFFFCC, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item howlite_wolf_spawn_egg = new SpawnEggItem(ModEntities.HOWLITE_WOLF, 0xDDDDDD, 0x3333FF, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item spellbound_elemental_spawn_egg = new SpawnEggItem(ModEntities.SPELLBOUND_ELEMENTAL, 0x885555, 0xCC33CC, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item rocky_luggeroth_spawn_egg = new SpawnEggItem(ModEntities.ROCKY_LUGGEROTH, 0xB07700, 0xCC9900, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item shalurker_spawn_egg = new SpawnEggItem(ModEntities.SHALURKER, 0x771177, 0x000000, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item muckling_spawn_egg = new SpawnEggItem(ModEntities.MUCKLING, 0xFF00FF, 0xCC66CC, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item markuzar_plant_spawn_egg = new SpawnEggItem(ModEntities.MARKUZAR_PLANT, 0x00FF66, 0xCC00FF, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item rugged_lurmorus_spawn_egg = new SpawnEggItem(ModEntities.RUGGED_LURMORUS, 0xCC9933, 0xFF6600, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item agate_golem_spawn_egg = new SpawnEggItem(ModEntities.AGATE_GOLEM, 0x660000, 0xBB5555, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item ancient_lagrahk_spawn_egg = new SpawnEggItem(ModEntities.ANCIENT_LAGRAHK, 0x772200, 0xAA5500, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item crystal_golem_spawn_egg = new SpawnEggItem(ModEntities.CRYSTAL_GOLEM, 0xFF66CC, 0xFF99CC, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item saltion_spawn_egg = new SpawnEggItem(ModEntities.SALTION, 0x6699FF, 0x6633FF, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item nomadic_lagrahk_spawn_egg = new SpawnEggItem(ModEntities.NOMADIC_LAGRAHK, 0x3366CC, 0x232323, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item shallow_arenthis_spawn_egg = new SpawnEggItem(ModEntities.SHALLOW_ARENTHIS, 0x6699CC, 0x003399, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item corrupt_sapper_spawn_egg = new SpawnEggItem(ModEntities.CORRUPT_SAPPER, 0x202020, 0xCC3300, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item contorted_naga_spawn_egg = new SpawnEggItem(ModEntities.CONTORTED_NAGA, 0x202020, 0xCC3300, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item lesser_spitfire_spawn_egg = new SpawnEggItem(ModEntities.LESSER_SPITFIRE, 0xFF00FF, 0x202020, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item lesser_shockshooter_spawn_egg = new SpawnEggItem(ModEntities.LESSER_SHOCKSHOOTER, 0x00FFFF, 202020, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item mineral_arenthis_spawn_egg = new SpawnEggItem(ModEntities.MINERAL_ARENTHIS, 0x0066CC, 0x000033, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item bismuth_uletrus_spawn_egg = new SpawnEggItem(ModEntities.BISMUTH_ULETRUS, 0x4E3863, 0x303030, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item archaic_warrior_spawn_egg = new SpawnEggItem(ModEntities.ARCHAIC_WARRIOR, 0x996699, 0xCC3366, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item primal_beast_spawn_egg = new SpawnEggItem(ModEntities.PRIMAL_BEAST, 0x006699, 0x66FFFF, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item cavern_tick_spawn_egg = new SpawnEggItem(ModEntities.CAVERN_TICK, 0x9966CC, 0x666699, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item blue_howlite_wolf_spawn_egg = new SpawnEggItem(ModEntities.BLUE_HOWLITE_WOLF, 0x0099CC, 0xCC00FF, (new Item.Properties()).group(ItemGroup.MISC));
    public static final Item malachite_guard_spawn_egg = new SpawnEggItem(ModEntities.MALACHITE_GUARD, 0x339900, 0x33CC99, (new Item.Properties()).group(ItemGroup.MISC));

    @SubscribeEvent
    public static void onRegisterItems(RegistryEvent.Register<Item> e) {
        final IForgeRegistry<Item> registry = e.getRegistry();

        registry.register(crystallized_redstone.setRegistryName("crystallized_redstone"));
        registry.register(crystallized_lapis_lazuli.setRegistryName("crystallized_lapis_lazuli"));
        registry.register(glint_and_gold.setRegistryName("glint_and_gold"));
        registry.register(agate_stick.setRegistryName("agate_stick"));
        registry.register(hot_dust.setRegistryName("hot_dust"));
        registry.register(goldstone_dust.setRegistryName("goldstone_dust"));
        registry.register(fine_dust.setRegistryName("fine_dust"));
        registry.register(cloudy_shard.setRegistryName("cloudy_shard"));
        registry.register(agate_cup.setRegistryName("agate_cup"));
        registry.register(scaynyx_ingot.setRegistryName("scaynyx_ingot"));
        registry.register(sweet_muckball.setRegistryName("sweet_muckball"));
        registry.register(sugar_crystals.setRegistryName("sugar_crystals"));
        registry.register(sugar_cluster.setRegistryName("sugar_cluster"));
        registry.register(shiny_bone.setRegistryName("shiny_bone"));
        registry.register(fine_thread.setRegistryName("fine_thread"));
        registry.register(twined_thread.setRegistryName("twined_thread"));
        registry.register(pink_essence.setRegistryName("pink_essence"));
        registry.register(pink_goo.setRegistryName("pink_goo"));
        registry.register(gemstone_pouch.setRegistryName("gemstone_pouch"));
        registry.register(agate_fabric.setRegistryName("agate_fabric"));
        registry.register(sturdy_pebble.setRegistryName("sturdy_pebble"));
        registry.register(scaynyx_bucket.setRegistryName("scaynyx_bucket"));
        registry.register(mineral_water_bucket.setRegistryName("mineral_water_bucket"));
        registry.register(superhot_magma_bucket.setRegistryName("superhot_magma_bucket"));
        registry.register(sweet_muck_bucket.setRegistryName("sweet_muck_bucket"));
        registry.register(liquid_bismuth_bucket.setRegistryName("liquid_bismuth_bucket"));
        registry.register(liquid_aura_bucket.setRegistryName("liquid_aura_bucket"));

        registry.register(pink_geode.setRegistryName("pink_geode"));
        registry.register(blue_geode.setRegistryName("blue_geode"));
        registry.register(green_geode.setRegistryName("green_geode"));
        registry.register(purple_geode.setRegistryName("purple_geode"));
        registry.register(pink_geode_slice.setRegistryName("pink_geode_slice"));
        registry.register(blue_geode_slice.setRegistryName("blue_geode_slice"));
        registry.register(green_geode_slice.setRegistryName("green_geode_slice"));
        registry.register(purple_geode_slice.setRegistryName("purple_geode_slice"));
        registry.register(pink_geode_juice.setRegistryName("pink_geode_juice"));
        registry.register(blue_geode_tea.setRegistryName("blue_geode_tea"));
        registry.register(green_geode_ale.setRegistryName("green_geode_ale"));
        registry.register(purple_geode_soda.setRegistryName("purple_geode_soda"));
        registry.register(pearly_geode_elixir.setRegistryName("pearly_geode_elixir"));
        registry.register(lurmorus_meat.setRegistryName("lurmorus_meat"));
        registry.register(lurmorus_steak.setRegistryName("lurmorus_steak"));
        registry.register(small_tentacle.setRegistryName("small_tentacle"));
        registry.register(small_calamari.setRegistryName("small_calamari"));
        registry.register(large_tentacle.setRegistryName("large_tentacle"));
        registry.register(large_calamari.setRegistryName("large_calamari"));
        registry.register(markuzar_mint.setRegistryName("markuzar_mint"));
        registry.register(luggeroth_chop.setRegistryName("luggeroth_chop"));
        registry.register(cooked_luggeroth_chop.setRegistryName("cooked_luggeroth_chop"));
        registry.register(tilipi.setRegistryName("tilipi"));
        registry.register(tilibl.setRegistryName("tilibl"));
        registry.register(tiligr.setRegistryName("tiligr"));
        registry.register(tilipu.setRegistryName("tilipu"));
        registry.register(tiliol.setRegistryName("tiliol"));
        registry.register(tilimy.setRegistryName("tilimy"));
        registry.register(plagued_tiliey.setRegistryName("plagued_tiliey"));
        registry.register(tiliou.setRegistryName("tiliou"));

        registry.register(hematite_powder.setRegistryName("hematite_powder"));
        registry.register(pyrite_powder.setRegistryName("pyrite_powder"));
        registry.register(labradorite_powder.setRegistryName("labradorite_powder"));
        registry.register(moonstone_powder.setRegistryName("moonstone_powder"));
        registry.register(cinnabar_powder.setRegistryName("cinnabar_powder"));
        registry.register(red_opal_powder.setRegistryName("red_opal_powder"));
        registry.register(blue_opal_powder.setRegistryName("blue_opal_powder"));
        registry.register(green_opal_powder.setRegistryName("green_opal_powder"));
        registry.register(white_opal_grit.setRegistryName("white_opal_grit"));

        registry.register(sugilite.setRegistryName("sugilite"));
        registry.register(hematite.setRegistryName("hematite"));
        registry.register(pyrite.setRegistryName("pyrite"));
        registry.register(labradorite.setRegistryName("labradorite"));
        registry.register(moonstone.setRegistryName("moonstone"));
        registry.register(cinnabar.setRegistryName("cinnabar"));
        registry.register(red_opal.setRegistryName("red_opal"));
        registry.register(blue_opal.setRegistryName("blue_opal"));
        registry.register(green_opal.setRegistryName("green_opal"));
        registry.register(white_opal.setRegistryName("white_opal"));
        registry.register(ixiolite.setRegistryName("ixiolite"));
        registry.register(proustite.setRegistryName("proustite"));
        registry.register(euclase.setRegistryName("euclase"));
        registry.register(leucite.setRegistryName("leucite"));
        registry.register(carnelian.setRegistryName("carnelian"));
        registry.register(benitoite.setRegistryName("benitoite"));
        registry.register(diopside.setRegistryName("diopside"));
        registry.register(chalcedony.setRegistryName("chalcedony"));
        registry.register(black_residue.setRegistryName("black_residue"));
        registry.register(tektite.setRegistryName("tektite"));
        registry.register(goldstone_residue.setRegistryName("goldstone_residue"));
        registry.register(goldstone.setRegistryName("goldstone"));
        registry.register(aura_residue.setRegistryName("aura_residue"));
        registry.register(aura_cluster.setRegistryName("aura_cluster"));
        registry.register(bismuth_residue.setRegistryName("bismuth_residue"));
        registry.register(bismuth_crystal.setRegistryName("bismuth_crystal"));

        registry.register(agate_sword.setRegistryName("agate_sword"));
        registry.register(agate_pickaxe.setRegistryName("agate_pickaxe"));
        registry.register(agate_axe.setRegistryName("agate_axe"));
        registry.register(agate_shovel.setRegistryName("agate_shovel"));
        registry.register(sugilite_sword.setRegistryName("sugilite_sword"));
        registry.register(sugilite_pickaxe.setRegistryName("sugilite_pickaxe"));
        registry.register(sugilite_axe.setRegistryName("sugilite_axe"));
        registry.register(sugilite_shovel.setRegistryName("sugilite_shovel"));
        registry.register(ixiolite_sword.setRegistryName("ixiolite_sword"));
        registry.register(ixiolite_pickaxe.setRegistryName("ixiolite_pickaxe"));
        registry.register(ixiolite_axe.setRegistryName("ixiolite_axe"));
        registry.register(ixiolite_shovel.setRegistryName("ixiolite_shovel"));
        registry.register(euclase_sword.setRegistryName("euclase_sword"));
        registry.register(euclase_pickaxe.setRegistryName("euclase_pickaxe"));
        registry.register(euclase_axe.setRegistryName("euclase_axe"));
        registry.register(euclase_shovel.setRegistryName("euclase_shovel"));
        registry.register(carnelian_sword.setRegistryName("carnelian_sword"));
        registry.register(carnelian_pickaxe.setRegistryName("carnelian_pickaxe"));
        registry.register(carnelian_axe.setRegistryName("carnelian_axe"));
        registry.register(carnelian_shovel.setRegistryName("carnelian_shovel"));
        registry.register(benitoite_sword.setRegistryName("benitoite_sword"));
        registry.register(benitoite_pickaxe.setRegistryName("benitoite_pickaxe"));
        registry.register(benitoite_axe.setRegistryName("benitoite_axe"));
        registry.register(benitoite_shovel.setRegistryName("benitoite_shovel"));
        registry.register(chalcedony_sword.setRegistryName("chalcedony_sword"));
        registry.register(chalcedony_pickaxe.setRegistryName("chalcedony_pickaxe"));
        registry.register(chalcedony_axe.setRegistryName("chalcedony_axe"));
        registry.register(chalcedony_shovel.setRegistryName("chalcedony_shovel"));
        registry.register(old_bow.setRegistryName("old_bow"));
        registry.register(agate_arrow.setRegistryName("agate_arrow"));

        registry.register(sugilite_helmet.setRegistryName("sugilite_helmet"));
        registry.register(sugilite_chestplate.setRegistryName("sugilite_chestplate"));
        registry.register(sugilite_legs.setRegistryName("sugilite_legs"));
        registry.register(sugilite_boots.setRegistryName("sugilite_boots"));
        registry.register(proustite_helmet.setRegistryName("proustite_helmet"));
        registry.register(proustite_chestplate.setRegistryName("proustite_chestplate"));
        registry.register(proustite_legs.setRegistryName("proustite_legs"));
        registry.register(proustite_boots.setRegistryName("proustite_boots"));
        registry.register(leucite_helmet.setRegistryName("leucite_helmet"));
        registry.register(leucite_chestplate.setRegistryName("leucite_chestplate"));
        registry.register(leucite_legs.setRegistryName("leucite_legs"));
        registry.register(leucite_boots.setRegistryName("leucite_boots"));
        registry.register(carnelian_helmet.setRegistryName("carnelian_helmet"));
        registry.register(carnelian_chestplate.setRegistryName("carnelian_chestplate"));
        registry.register(carnelian_legs.setRegistryName("carnelian_legs"));
        registry.register(carnelian_boots.setRegistryName("carnelian_boots"));
        registry.register(diopside_helmet.setRegistryName("diopside_helmet"));
        registry.register(diopside_chestplate.setRegistryName("diopside_chestplate"));
        registry.register(diopside_legs.setRegistryName("diopside_legs"));
        registry.register(diopside_boots.setRegistryName("diopside_boots"));
        registry.register(chalcedony_helmet.setRegistryName("chalcedony_helmet"));
        registry.register(chalcedony_chestplate.setRegistryName("chalcedony_chestplate"));
        registry.register(chalcedony_legs.setRegistryName("chalcedony_legs"));
        registry.register(chalcedony_boots.setRegistryName("chalcedony_boots"));

        registry.register(malachite_guard_headgear.setRegistryName("malachite_guard_headgear"));
        registry.register(malachite_guard_brace.setRegistryName("malachite_guard_brace"));
        registry.register(malachite_guard_gear.setRegistryName("malachite_guard_gear"));
        registry.register(malachite_guard_boots.setRegistryName("malachite_guard_boots"));
        registry.register(apex_predator_hood.setRegistryName("apex_predator_hood"));
        registry.register(apex_predator_jacket.setRegistryName("apex_predator_jacket"));
        registry.register(apex_predator_trousers.setRegistryName("apex_predator_trousers"));
        registry.register(apex_predator_boots.setRegistryName("apex_predator_boots"));
        registry.register(spinel_princess_cowl.setRegistryName("spinel_princess_cowl"));
        registry.register(spinel_princess_cloak.setRegistryName("spinel_princess_cloak"));
        registry.register(spinel_princess_dress.setRegistryName("spinel_princess_dress"));
        registry.register(spinel_princess_heels.setRegistryName("spinel_princess_heels"));
        registry.register(zircon_prince_crown.setRegistryName("zircon_prince_crown"));
        registry.register(zircon_prince_chestpiece.setRegistryName("zircon_prince_chestpiece"));
        registry.register(zircon_prince_gear.setRegistryName("zircon_prince_gear"));
        registry.register(zircon_prince_boots.setRegistryName("zircon_prince_boots"));
        registry.register(corrupt_warrior_helm.setRegistryName("corrupt_warrior_helm"));
        registry.register(corrupt_warrior_guard.setRegistryName("corrupt_warrior_guard"));
        registry.register(corrupt_warrior_greaves.setRegistryName("corrupt_warrior_greaves"));
        registry.register(corrupt_warrior_boots.setRegistryName("corrupt_warrior_boots"));
        registry.register(gaia_duchess_helm.setRegistryName("gaia_duchess_helm"));
        registry.register(gaia_duchess_guard.setRegistryName("gaia_duchess_guard"));
        registry.register(gaia_duchess_greaves.setRegistryName("gaia_duchess_greaves"));
        registry.register(gaia_duchess_boots.setRegistryName("gaia_duchess_boots"));
        registry.register(gaia_baron_mask.setRegistryName("gaia_baron_mask"));
        registry.register(gaia_baron_tuxedo.setRegistryName("gaia_baron_tuxedo"));
        registry.register(gaia_baron_pants.setRegistryName("gaia_baron_pants"));
        registry.register(gaia_baron_shoes.setRegistryName("gaia_baron_shoes"));
        registry.register(gaia_duke_helm.setRegistryName("gaia_duke_helm"));
        registry.register(gaia_duke_guard.setRegistryName("gaia_duke_guard"));
        registry.register(gaia_duke_greaves.setRegistryName("gaia_duke_greaves"));
        registry.register(gaia_duke_boots.setRegistryName("gaia_duke_boots"));
        registry.register(gaia_champion_helm.setRegistryName("gaia_champion_helm"));
        registry.register(gaia_champion_guard.setRegistryName("gaia_champion_guard"));
        registry.register(gaia_champion_greaves.setRegistryName("gaia_champion_greaves"));
        registry.register(gaia_champion_boots.setRegistryName("gaia_champion_boots"));

        registry.register(malachite_guard_baton.setRegistryName("malachite_guard_baton"));
        registry.register(apex_predator_mace.setRegistryName("apex_predator_mace"));
        registry.register(spinel_princess_flamberge.setRegistryName("spinel_princess_flamberge"));
        registry.register(zircon_prince_razor.setRegistryName("zircon_prince_razor"));
        registry.register(corrupt_warrior_sword.setRegistryName("corrupt_warrior_sword"));
        registry.register(gaia_duchess_khopesh.setRegistryName("gaia_duchess_khopesh"));
        registry.register(gaia_baron_dagger.setRegistryName("gaia_baron_dagger"));
        registry.register(gaia_duke_blade.setRegistryName("gaia_duke_blade"));
        registry.register(gaia_champion_sword.setRegistryName("gaia_champion_sword"));

        registry.register(growth_sapper_spawn_egg.setRegistryName("growth_sapper_spawn_egg"));
        registry.register(mutant_growth_extractor_spawn_egg.setRegistryName("mutant_growth_extractor_spawn_egg"));
        registry.register(howlite_wolf_spawn_egg.setRegistryName("howlite_wolf_spawn_egg"));
        registry.register(spellbound_elemental_spawn_egg.setRegistryName("spellbound_elemental_spawn_egg"));
        registry.register(rocky_luggeroth_spawn_egg.setRegistryName("rocky_luggeroth_spawn_egg"));
        registry.register(shalurker_spawn_egg.setRegistryName("shalurker_spawn_egg"));
        registry.register(muckling_spawn_egg.setRegistryName("muckling_spawn_egg"));
        registry.register(markuzar_plant_spawn_egg.setRegistryName("markuzar_plant_spawn_egg"));
        registry.register(rugged_lurmorus_spawn_egg.setRegistryName("rugged_lurmorus_spawn_egg"));
        registry.register(agate_golem_spawn_egg.setRegistryName("agate_golem_spawn_egg"));
        registry.register(ancient_lagrahk_spawn_egg.setRegistryName("ancient_lagrahk_spawn_egg"));
        registry.register(crystal_golem_spawn_egg.setRegistryName("crystal_golem_spawn_egg"));
        registry.register(saltion_spawn_egg.setRegistryName("saltion_spawn_egg"));
        registry.register(nomadic_lagrahk_spawn_egg.setRegistryName("nomadic_lagrahk_spawn_egg"));
        registry.register(shallow_arenthis_spawn_egg.setRegistryName("shallow_arenthis_spawn_egg"));
        registry.register(corrupt_sapper_spawn_egg.setRegistryName("corrupt_sapper_spawn_egg"));
        registry.register(contorted_naga_spawn_egg.setRegistryName("contorted_naga_spawn_egg"));
        registry.register(lesser_spitfire_spawn_egg.setRegistryName("lesser_spitfire_spawn_egg"));
        registry.register(lesser_shockshooter_spawn_egg.setRegistryName("lesser_shockshooter_spawn_egg"));
        registry.register(mineral_arenthis_spawn_egg.setRegistryName("mineral_arenthis_spawn_egg"));
        registry.register(bismuth_uletrus_spawn_egg.setRegistryName("bismuth_uletrus_spawn_egg"));
        registry.register(archaic_warrior_spawn_egg.setRegistryName("archaic_warrior_spawn_egg"));
        registry.register(primal_beast_spawn_egg.setRegistryName("primal_beast_spawn_egg"));
        registry.register(cavern_tick_spawn_egg.setRegistryName("cavern_tick_spawn_egg"));
        registry.register(blue_howlite_wolf_spawn_egg.setRegistryName("blue_howlite_wolf_spawn_egg"));
        registry.register(malachite_guard_spawn_egg.setRegistryName("malachite_guard_spawn_egg"));

        /*
         * Blocks
         */
        //Utility Blocks
        registry.register(registerBlock(ModBlocks.keystone_block));
        registry.register(new WallOrFloorItem(ModBlocks.pyrite_torch, ModBlocks.pyrite_wall_torch, new Item.Properties().group(GaiaItemGroups.GAIA_BLOCKS)).setRegistryName("pyrite_torch"));
        registry.register(registerBlock(ModBlocks.agate_crafting_table));
        registry.register(registerBlock(ModBlocks.crude_storage_crate));
        registry.register(registerBlock(ModBlocks.mega_storage_crate));
        registry.register(registerBlock(ModBlocks.gaia_stone_furnace));
        registry.register(registerBlock(ModBlocks.restructurer));
        registry.register(registerBlock(ModBlocks.purifier));

        //Natural Blocks
        registry.register(registerBlock(ModBlocks.heavy_soil));
        registry.register(registerBlock(ModBlocks.corrupt_soil));
        registry.register(registerBlock(ModBlocks.boggy_soil));
        registry.register(registerBlock(ModBlocks.light_soil));
        registry.register(registerBlock(ModBlocks.glitter_grass));
        registry.register(registerBlock(ModBlocks.corrupt_grass));
        registry.register(registerBlock(ModBlocks.murky_grass));
        registry.register(registerBlock(ModBlocks.soft_grass));
        registry.register(registerBlock(ModBlocks.frail_glitter_block));
        registry.register(registerBlock(ModBlocks.thick_glitter_block));
        registry.register(registerBlock(ModBlocks.gummy_glitter_block));
        registry.register(registerBlock(ModBlocks.pink_sludge_block));

        //Plants
        registry.register(registerBlock(ModBlocks.crystal_growth));
        registry.register(registerBlock(ModBlocks.crystal_growth_red));
        registry.register(registerBlock(ModBlocks.crystal_growth_black));
        registry.register(registerBlock(ModBlocks.crystal_growth_seared));
        registry.register(registerBlock(ModBlocks.crystal_growth_mutant));
        registry.register(registerBlock(ModBlocks.crystal_growth_aura));
        registry.register(registerBlock(ModBlocks.thiscus));
        registry.register(registerBlock(ModBlocks.ouzium));
        registry.register(registerBlock(ModBlocks.agathum));
        registry.register(registerBlock(ModBlocks.varloom));
        registry.register(registerBlock(ModBlocks.corrupted_varloom));
        registry.register(registerBlock(ModBlocks.missingno_plant));
        registry.register(registerBlock(ModBlocks.spotted_kersei));
        registry.register(registerBlock(ModBlocks.thorny_wiltha));
        registry.register(registerBlock(ModBlocks.roofed_agaric));
        registry.register(registerBlock(ModBlocks.bulbous_hobina));
        registry.register(registerBlock(ModBlocks.stickly_cupsir));
        registry.register(registerBlock(ModBlocks.mystical_murgni));
        registry.register(registerBlock(ModBlocks.corrupted_gaia_eye));
        //registry.register(registerBlock(ModBlocks.sacred_gaia_eye));
        registry.register(registerBlock(ModBlocks.elder_imklia));
        registry.register(registerBlock(ModBlocks.gold_orb_tucher));
        registry.register(registerBlock(ModBlocks.missingno_fungus));

        registry.register(registerBlock(ModBlocks.pink_agate_sapling));
        registry.register(registerBlock(ModBlocks.blue_agate_sapling));
        registry.register(registerBlock(ModBlocks.green_agate_sapling));
        registry.register(registerBlock(ModBlocks.purple_agate_sapling));
        registry.register(registerBlock(ModBlocks.fossilized_sapling));
        registry.register(registerBlock(ModBlocks.corrupted_sapling));
        registry.register(registerBlock(ModBlocks.burnt_sapling));
        registry.register(registerBlock(ModBlocks.burning_sapling));
        registry.register(registerBlock(ModBlocks.aura_sapling));
        registry.register(registerBlock(ModBlocks.pink_agate_leaves));
        registry.register(registerBlock(ModBlocks.blue_agate_leaves));
        registry.register(registerBlock(ModBlocks.green_agate_leaves));
        registry.register(registerBlock(ModBlocks.purple_agate_leaves));
        registry.register(registerBlock(ModBlocks.fossilized_leaves));
        registry.register(registerBlock(ModBlocks.corrupted_leaves));
        registry.register(registerBlock(ModBlocks.burnt_leaves));
        registry.register(registerBlock(ModBlocks.burning_leaves, 200));
        registry.register(registerBlock(ModBlocks.aura_leaves));
        registry.register(registerBlock(ModBlocks.pink_agate_log));
        registry.register(registerBlock(ModBlocks.blue_agate_log));
        registry.register(registerBlock(ModBlocks.green_agate_log));
        registry.register(registerBlock(ModBlocks.purple_agate_log));
        registry.register(registerBlock(ModBlocks.fossilized_log));
        registry.register(registerBlock(ModBlocks.corrupted_log));
        registry.register(registerBlock(ModBlocks.burnt_log));
        registry.register(registerBlock(ModBlocks.burning_log, 1600));
        registry.register(registerBlock(ModBlocks.aura_log));
        registry.register(registerBlock(ModBlocks.stripped_pink_agate_log));
        registry.register(registerBlock(ModBlocks.stripped_blue_agate_log));
        registry.register(registerBlock(ModBlocks.stripped_green_agate_log));
        registry.register(registerBlock(ModBlocks.stripped_purple_agate_log));
        registry.register(registerBlock(ModBlocks.stripped_fossilized_log));
        registry.register(registerBlock(ModBlocks.stripped_corrupted_log));
        registry.register(registerBlock(ModBlocks.stripped_burnt_log));
        registry.register(registerBlock(ModBlocks.stripped_burning_log, 1600));
        registry.register(registerBlock(ModBlocks.stripped_aura_log));
        registry.register(registerBlock(ModBlocks.pink_agate_wood));
        registry.register(registerBlock(ModBlocks.blue_agate_wood));
        registry.register(registerBlock(ModBlocks.green_agate_wood));
        registry.register(registerBlock(ModBlocks.purple_agate_wood));
        registry.register(registerBlock(ModBlocks.fossilized_wood));
        registry.register(registerBlock(ModBlocks.corrupted_wood));
        registry.register(registerBlock(ModBlocks.burnt_wood));
        registry.register(registerBlock(ModBlocks.burning_wood, 1600));
        registry.register(registerBlock(ModBlocks.aura_wood));

        registry.register(registerBlock(ModBlocks.salt));
        registry.register(registerBlock(ModBlocks.saltstone));
        registry.register(registerBlock(ModBlocks.pebbles));
        registry.register(registerBlock(ModBlocks.gaia_stone));
        registry.register(registerBlock(ModBlocks.gaia_cobblestone));
        registry.register(registerBlock(ModBlocks.wasteland_stone));
        registry.register(registerBlock(ModBlocks.static_stone));
        registry.register(registerBlock(ModBlocks.charged_mineral));
        registry.register(registerBlock(ModBlocks.volcanic_rock));
        registry.register(registerBlock(ModBlocks.searing_rock));
        registry.register(registerBlock(ModBlocks.primal_mass));
        registry.register(registerBlock(ModBlocks.impure_rock));
        registry.register(registerBlock(ModBlocks.active_rock));
        registry.register(registerBlock(ModBlocks.impure_sludge));
        registry.register(registerBlock(ModBlocks.geyser_block));
        registry.register(registerBlock(ModBlocks.sparkling_rock));
        registry.register(registerBlock(ModBlocks.aura_shoot));

        //Planks
        registry.register(registerBlock(ModBlocks.pink_agate_planks));
        registry.register(registerBlock(ModBlocks.blue_agate_planks));
        registry.register(registerBlock(ModBlocks.green_agate_planks));
        registry.register(registerBlock(ModBlocks.purple_agate_planks));
        registry.register(registerBlock(ModBlocks.fossilized_planks));
        registry.register(registerBlock(ModBlocks.corrupted_planks));
        registry.register(registerBlock(ModBlocks.burnt_planks));
        registry.register(registerBlock(ModBlocks.burning_planks));
        registry.register(registerBlock(ModBlocks.aura_planks));
        registry.register(registerBlock(ModBlocks.pink_agate_plank_slab));
        registry.register(registerBlock(ModBlocks.blue_agate_plank_slab));
        registry.register(registerBlock(ModBlocks.green_agate_plank_slab));
        registry.register(registerBlock(ModBlocks.purple_agate_plank_slab));
        registry.register(registerBlock(ModBlocks.fossilized_plank_slab));
        registry.register(registerBlock(ModBlocks.corrupted_plank_slab));
        registry.register(registerBlock(ModBlocks.burnt_plank_slab));
        registry.register(registerBlock(ModBlocks.burning_plank_slab));
        registry.register(registerBlock(ModBlocks.aura_plank_slab));
        registry.register(registerBlock(ModBlocks.pink_agate_plank_stairs));
        registry.register(registerBlock(ModBlocks.blue_agate_plank_stairs));
        registry.register(registerBlock(ModBlocks.green_agate_plank_stairs));
        registry.register(registerBlock(ModBlocks.purple_agate_plank_stairs));
        registry.register(registerBlock(ModBlocks.fossilized_plank_stairs));
        registry.register(registerBlock(ModBlocks.corrupted_plank_stairs));
        registry.register(registerBlock(ModBlocks.burnt_plank_stairs));
        registry.register(registerBlock(ModBlocks.burning_plank_stairs));
        registry.register(registerBlock(ModBlocks.aura_plank_stairs));

        registry.register(registerBlock(ModBlocks.cloudy_glass));
        registry.register(registerBlock(ModBlocks.foggy_glass));
        registry.register(registerBlock(ModBlocks.gaia_stone_bricks));
        registry.register(registerBlock(ModBlocks.cracked_gaia_stone_bricks));
        registry.register(registerBlock(ModBlocks.crusted_gaia_stone_bricks));
        registry.register(registerBlock(ModBlocks.reinforced_bricks));
        registry.register(registerBlock(ModBlocks.malachite_bricks));
        registry.register(registerBlock(ModBlocks.malachite_cracked_bricks));
        registry.register(registerBlock(ModBlocks.malachite_crusted_bricks));
        registry.register(registerBlock(ModBlocks.malachite_floor_tiles));
        registry.register(registerBlock(ModBlocks.malachite_chisel_bricks));
        registry.register(registerBlock(ModBlocks.malachite_pulsing_bricks));
        registry.register(registerBlock(ModBlocks.malachite_pulsing_tiles));
        registry.register(registerBlock(ModBlocks.malachite_pulsing_chisel));
        registry.register(registerBlock(ModBlocks.malachite_brick_slab));
        registry.register(registerBlock(ModBlocks.malachite_floor_slab));
        registry.register(registerBlock(ModBlocks.malachite_pillar));
        registry.register(registerBlock(ModBlocks.malachite_brick_stairs));
        registry.register(registerBlock(ModBlocks.malachite_chisel_stairs));
        registry.register(registerBlock(ModBlocks.malachite_pulsing_brick_stairs));
        registry.register(registerBlock(ModBlocks.malachite_pillar_stairs));
        registry.register(registerBlock(ModBlocks.malachite_floor_stairs));
        registry.register(registerBlock(ModBlocks.malachite_pulsing_floor_stairs));
        registry.register(registerBlock(ModBlocks.malachite_pulsing_chisel_stairs));
        registry.register(registerBlock(ModBlocks.bolstered_bricks));

        registry.register(registerBlock(ModBlocks.opal_block_red));
        registry.register(registerBlock(ModBlocks.opal_block_blue));
        registry.register(registerBlock(ModBlocks.opal_block_green));
        registry.register(registerBlock(ModBlocks.opal_block_white));
        registry.register(registerBlock(ModBlocks.sugilite_block));
        registry.register(registerBlock(ModBlocks.hematite_block));
        registry.register(registerBlock(ModBlocks.labradorite_block));
        registry.register(registerBlock(ModBlocks.pyrite_block));
        registry.register(registerBlock(ModBlocks.moonstone_block));
        registry.register(registerBlock(ModBlocks.cinnabar_block));
        registry.register(registerBlock(ModBlocks.tektite_block));
        registry.register(registerBlock(ModBlocks.goldstone_block));
        registry.register(registerBlock(ModBlocks.aura_block));
        registry.register(registerBlock(ModBlocks.bismuth_block));
        registry.register(registerBlock(ModBlocks.ixiolite_block));
        registry.register(registerBlock(ModBlocks.proustite_block));
        registry.register(registerBlock(ModBlocks.euclase_block));
        registry.register(registerBlock(ModBlocks.leucite_block));
        registry.register(registerBlock(ModBlocks.carnelian_block));
        registry.register(registerBlock(ModBlocks.benitoite_block));
        registry.register(registerBlock(ModBlocks.diopside_block));
        registry.register(registerBlock(ModBlocks.chalcedony_block));

        registry.register(registerBlock(ModBlocks.sugilite_ore));
        registry.register(registerBlock(ModBlocks.hematite_ore));
        registry.register(registerBlock(ModBlocks.pyrite_ore));
        registry.register(registerBlock(ModBlocks.opal_ore_red));
        registry.register(registerBlock(ModBlocks.opal_ore_blue));
        registry.register(registerBlock(ModBlocks.opal_ore_green));
        registry.register(registerBlock(ModBlocks.opal_ore_white));
        registry.register(registerBlock(ModBlocks.labradorite_ore));
        registry.register(registerBlock(ModBlocks.moonstone_ore));
        registry.register(registerBlock(ModBlocks.cinnabar_ore));
        registry.register(registerBlock(ModBlocks.speckled_rock));
        registry.register(registerBlock(ModBlocks.coarse_rock));
        registry.register(registerBlock(ModBlocks.precious_rock));
    }

    private static Item registerBlock(Block block) {
        return registerBlock(block, 0);
    }

    private static Item registerBlock(Block block, int burnTime) {
        if (burnTime == 0) {
            return new BlockItem(block, new Item.Properties().group(GaiaItemGroups.GAIA_BLOCKS)).setRegistryName(block.getRegistryName());
        } else {
            return new BlockItem(block, new Item.Properties().group(GaiaItemGroups.GAIA_BLOCKS)) {
                @Override
                public int getBurnTime(ItemStack stack) {
                    return burnTime;
                }
            }.setRegistryName(block.getRegistryName());
        }
    }
}
