package androsa.gaiadimension.registry;

import androsa.gaiadimension.GaiaDimension;
import androsa.gaiadimension.item.*;
import androsa.gaiadimension.item.armor.*;
import androsa.gaiadimension.item.tools.*;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.registries.ObjectHolder;

import static net.minecraft.inventory.EquipmentSlotType.*;

@ObjectHolder(GaiaDimension.MODID)
@SuppressWarnings("unused")
public class ModItems {

    public static final Item crystallized_redstone = new BasicGaiaItem();
    public static final Item crystallized_lapis_lazuli = new BasicGaiaItem();
    public static final Item glint_and_gold = new GlintAndGoldItem();
    public static final Item agate_stick = new BasicGaiaItem();
    public static final Item hot_dust = new BasicGaiaItem() {
        @Override
        public int getBurnTime(ItemStack stack) {
            return 100;
        }
    };
    public static final Item goldstone_dust = new BasicGaiaItem();
    public static final Item fine_dust = new BasicGaiaItem();
    public static final Item cloudy_shard = new BasicGaiaItem();
    public static final Item agate_cup = new BasicGaiaItem();
    public static final Item scaynyx_ingot = new BasicGaiaItem();
    public static final Item sweet_muckball = new BasicGaiaItem();
    public static final Item sugar_crystals = new BasicGaiaItem();
    public static final Item sugar_cluster = new BasicGaiaItem();
    public static final Item shiny_bone = new BasicGaiaItem();
    public static final Item fine_thread = new BasicGaiaItem();
    public static final Item twined_thread = new BasicGaiaItem();
    public static final Item pink_essence = new BasicGaiaItem();
    public static final Item pink_goo = new BasicGaiaItem();
    public static final Item gemstone_pouch = new GemstonePouchItem();
    public static final Item agate_fabric = new BasicGaiaItem();
    public static final Item sturdy_pebble = new SturdyPebbleItem();
    public static final Item scaynyx_bucket = new ScaynyxBucketItem();

    public static final Item pink_geode = new BasicGaiaItem();
    public static final Item blue_geode = new BasicGaiaItem();
    public static final Item green_geode = new BasicGaiaItem();
    public static final Item purple_geode = new BasicGaiaItem();
    public static final Item pink_geode_slice = new GeodeSliceItem(ModFoods.PINK_SLICE);
    public static final Item blue_geode_slice = new GeodeSliceItem(ModFoods.BLUE_SLICE);
    public static final Item green_geode_slice = new GeodeSliceItem(ModFoods.GREEN_SLICE);
    public static final Item purple_geode_slice = new GeodeSliceItem(ModFoods.PURPLE_SLICE);
    public static final Item pink_geode_juice = new GeodeJuiceItem(ModFoods.PINK_JUICE);
    public static final Item blue_geode_tea = new GeodeJuiceItem(ModFoods.BLUE_TEA);
    public static final Item green_geode_ale = new GeodeJuiceItem(ModFoods.GREEN_ALE);
    public static final Item purple_geode_soda = new GeodeJuiceItem(ModFoods.PURPLE_SODA);
    public static final Item pearly_geode_elixir = new GeodeJuiceItem(ModFoods.PEARLY_ELIXIR);
    public static final Item lurmorus_meat = new BasicGaiaItem(ModFoods.LURMORUS_MEAT);
    public static final Item lurmorus_steak = new BasicGaiaItem(ModFoods.LURMORUS_STEAK);
    public static final Item small_tentacle = new BasicGaiaItem(ModFoods.SMALL_TENTACLE);
    public static final Item small_calamari = new BasicGaiaItem(ModFoods.SMALL_CALAMARI);
    public static final Item large_tentacle = new BasicGaiaItem(ModFoods.LARGE_TENTACLE);
    public static final Item large_calamari = new BasicGaiaItem(ModFoods.LARGE_CALAMARI);
    public static final Item markuzar_mint = new BasicGaiaItem(ModFoods.MARKUZAR_MINT);
    public static final Item luggeroth_chop = new BasicGaiaItem(ModFoods.LUGGEROTH_CHOP);
    public static final Item cooked_luggeroth_chop = new BasicGaiaItem(ModFoods.COOKED_LUGGEROTH_CHOP);
    public static final Item tilipi = new BasicGaiaItem(ModFoods.TILIPI);
    public static final Item tilibl = new BasicGaiaItem(ModFoods.TILIBL);
    public static final Item tiligr = new BasicGaiaItem(ModFoods.TILIGR);
    public static final Item tilipu = new BasicGaiaItem(ModFoods.TILIPU);
    public static final Item tiliol = new BasicGaiaItem(ModFoods.TILIOL);
    public static final Item tilimy = new BasicGaiaItem(ModFoods.TILIMY);
    public static final Item plagued_tiliey = new BasicGaiaItem(ModFoods.PLAGUED_TILIEY);
    public static final Item tiliou = new BasicGaiaItem(ModFoods.TILIOU);

    public static final Item hematite_powder = new GroundGemItem();
    public static final Item pyrite_powder = new GroundGemItem();
    public static final Item labradorite_powder = new GroundGemItem();
    public static final Item moonstone_powder = new GroundGemItem();
    public static final Item cinnabar_powder = new GroundGemItem();
    public static final Item red_opal_powder = new GroundGemItem();
    public static final Item blue_opal_powder = new GroundGemItem();
    public static final Item green_opal_powder = new GroundGemItem();
    public static final Item white_opal_grit = new GroundGemItem();

    public static final Item sugilite = new BasicGaiaItem();
    public static final Item hematite = new BasicGaiaItem();
    public static final Item pyrite = new BasicGaiaItem();
    public static final Item labradorite = new BasicGaiaItem();
    public static final Item moonstone = new BasicGaiaItem();
    public static final Item cinnabar = new BasicGaiaItem();
    public static final Item red_opal = new BasicGaiaItem();
    public static final Item blue_opal = new BasicGaiaItem();
    public static final Item green_opal = new BasicGaiaItem();
    public static final Item white_opal = new BasicGaiaItem();
    public static final Item ixiolite = new BasicGaiaItem();
    public static final Item proustite = new BasicGaiaItem();
    public static final Item euclase = new BasicGaiaItem();
    public static final Item leucite = new BasicGaiaItem();
    public static final Item carnelian = new BasicGaiaItem();
    public static final Item benitoite = new BasicGaiaItem();
    public static final Item diopside = new BasicGaiaItem();
    public static final Item chalcedony = new BasicGaiaItem();
    public static final Item black_residue = new BasicGaiaItem();
    public static final Item tektite = new BasicGaiaItem();
    public static final Item goldstone = new BasicGaiaItem();
    public static final Item goldstone_residue = new BasicGaiaItem();
    public static final Item aura_residue = new BasicGaiaItem();
    public static final Item aura_cluster = new BasicGaiaItem();
    public static final Item bismuth_residue = new BasicGaiaItem();
    public static final Item bismuth_crystal = new BasicGaiaItem();

    public static final Item sugilite_helmet = new BasicGaiaArmorItem(GaiaArmorMaterials.SUGILITE, HEAD);
    public static final Item sugilite_chestplate = new BasicGaiaArmorItem(GaiaArmorMaterials.SUGILITE, CHEST);
    public static final Item sugilite_legs = new BasicGaiaArmorItem(GaiaArmorMaterials.SUGILITE, LEGS);
    public static final Item sugilite_boots = new BasicGaiaArmorItem(GaiaArmorMaterials.SUGILITE, FEET);
    public static final Item proustite_helmet = new BasicGaiaArmorItem(GaiaArmorMaterials.PROUSTITE, HEAD);
    public static final Item proustite_chestplate = new BasicGaiaArmorItem(GaiaArmorMaterials.PROUSTITE, CHEST);
    public static final Item proustite_legs = new BasicGaiaArmorItem(GaiaArmorMaterials.PROUSTITE, LEGS);
    public static final Item proustite_boots = new BasicGaiaArmorItem(GaiaArmorMaterials.PROUSTITE, FEET);
    public static final Item leucite_helmet = new BasicGaiaArmorItem(GaiaArmorMaterials.LEUCITE, HEAD);
    public static final Item leucite_chestplate = new BasicGaiaArmorItem(GaiaArmorMaterials.LEUCITE, CHEST);
    public static final Item leucite_legs = new BasicGaiaArmorItem(GaiaArmorMaterials.LEUCITE, LEGS);
    public static final Item leucite_boots = new BasicGaiaArmorItem(GaiaArmorMaterials.LEUCITE, FEET);
    public static final Item carnelian_helmet = new BasicGaiaArmorItem(GaiaArmorMaterials.CARNELIAN, HEAD);
    public static final Item carnelian_chestplate = new BasicGaiaArmorItem(GaiaArmorMaterials.CARNELIAN, CHEST);
    public static final Item carnelian_legs = new BasicGaiaArmorItem(GaiaArmorMaterials.CARNELIAN, LEGS);
    public static final Item carnelian_boots = new BasicGaiaArmorItem(GaiaArmorMaterials.CARNELIAN, FEET);
    public static final Item diopside_helmet = new BasicGaiaArmorItem(GaiaArmorMaterials.DIOPSIDE, HEAD);
    public static final Item diopside_chestplate = new BasicGaiaArmorItem(GaiaArmorMaterials.DIOPSIDE, CHEST);
    public static final Item diopside_legs = new BasicGaiaArmorItem(GaiaArmorMaterials.DIOPSIDE, LEGS);
    public static final Item diopside_boots = new BasicGaiaArmorItem(GaiaArmorMaterials.DIOPSIDE, FEET);
    public static final Item chalcedony_helmet = new BasicGaiaArmorItem(GaiaArmorMaterials.CHALCEDONY, HEAD);
    public static final Item chalcedony_chestplate = new BasicGaiaArmorItem(GaiaArmorMaterials.CHALCEDONY, CHEST);
    public static final Item chalcedony_legs = new BasicGaiaArmorItem(GaiaArmorMaterials.CHALCEDONY, LEGS);
    public static final Item chalcedony_boots = new BasicGaiaArmorItem(GaiaArmorMaterials.CHALCEDONY, FEET);

    public static final Item malachite_guard_headgear = new MalachiteGuardArmorItem(GaiaArmorMaterials.MALACHITE, HEAD);
    public static final Item malachite_guard_brace = new MalachiteGuardArmorItem(GaiaArmorMaterials.MALACHITE, CHEST);
    public static final Item malachite_guard_gear = new MalachiteGuardArmorItem(GaiaArmorMaterials.MALACHITE, LEGS);
    public static final Item malachite_guard_boots = new MalachiteGuardArmorItem(GaiaArmorMaterials.MALACHITE, FEET);
    public static final Item apex_predator_hood = new ApexPredatorArmorItem(GaiaArmorMaterials.TIGER_EYE, HEAD);
    public static final Item apex_predator_jacket = new ApexPredatorArmorItem(GaiaArmorMaterials.TIGER_EYE, CHEST);
    public static final Item apex_predator_trousers = new ApexPredatorArmorItem(GaiaArmorMaterials.TIGER_EYE, LEGS);
    public static final Item apex_predator_boots = new ApexPredatorArmorItem(GaiaArmorMaterials.TIGER_EYE, FEET);
    public static final Item spinel_princess_cowl = new SpinelPrincessArmorItem(GaiaArmorMaterials.SPINEL, HEAD);
    public static final Item spinel_princess_cloak = new SpinelPrincessArmorItem(GaiaArmorMaterials.SPINEL, CHEST);
    public static final Item spinel_princess_dress = new SpinelPrincessArmorItem(GaiaArmorMaterials.SPINEL, LEGS);
    public static final Item spinel_princess_heels = new SpinelPrincessArmorItem(GaiaArmorMaterials.SPINEL, FEET);
    public static final Item zircon_prince_crown = new ZirconPrinceArmorItem(GaiaArmorMaterials.ZIRCON, HEAD);
    public static final Item zircon_prince_chestpiece = new ZirconPrinceArmorItem(GaiaArmorMaterials.ZIRCON, CHEST);
    public static final Item zircon_prince_gear = new ZirconPrinceArmorItem(GaiaArmorMaterials.ZIRCON, LEGS);
    public static final Item zircon_prince_boots = new ZirconPrinceArmorItem(GaiaArmorMaterials.ZIRCON, FEET);
    public static final Item corrupt_warrior_helm = new CorruptWarriorArmorItem(GaiaArmorMaterials.CORRUPT, HEAD);
    public static final Item corrupt_warrior_guard = new CorruptWarriorArmorItem(GaiaArmorMaterials.CORRUPT, CHEST);
    public static final Item corrupt_warrior_greaves = new CorruptWarriorArmorItem(GaiaArmorMaterials.CORRUPT, LEGS);
    public static final Item corrupt_warrior_boots = new CorruptWarriorArmorItem(GaiaArmorMaterials.CORRUPT, FEET);
    public static final Item gaia_duchess_helm = new GaiaDuchessArmorItem(GaiaArmorMaterials.BIXBITE, HEAD);
    public static final Item gaia_duchess_guard = new GaiaDuchessArmorItem(GaiaArmorMaterials.BIXBITE, CHEST);
    public static final Item gaia_duchess_greaves = new GaiaDuchessArmorItem(GaiaArmorMaterials.BIXBITE, LEGS);
    public static final Item gaia_duchess_boots = new GaiaDuchessArmorItem(GaiaArmorMaterials.BIXBITE, FEET);
    public static final Item gaia_baron_mask = new GaiaBaronArmorItem(GaiaArmorMaterials.TSAVORITE, HEAD);
    public static final Item gaia_baron_tuxedo = new GaiaBaronArmorItem(GaiaArmorMaterials.TSAVORITE, CHEST);
    public static final Item gaia_baron_pants = new GaiaBaronArmorItem(GaiaArmorMaterials.TSAVORITE, LEGS);
    public static final Item gaia_baron_shoes = new GaiaBaronArmorItem(GaiaArmorMaterials.TSAVORITE, FEET);
    public static final Item gaia_duke_helm = new GaiaDukeArmorItem(GaiaArmorMaterials.LARVIKITE, HEAD);
    public static final Item gaia_duke_guard = new GaiaDukeArmorItem(GaiaArmorMaterials.LARVIKITE, CHEST);
    public static final Item gaia_duke_greaves = new GaiaDukeArmorItem(GaiaArmorMaterials.LARVIKITE, LEGS);
    public static final Item gaia_duke_boots = new GaiaDukeArmorItem(GaiaArmorMaterials.LARVIKITE, FEET);
    public static final Item gaia_champion_helm = new GaiaChampArmorItem(GaiaArmorMaterials.GAIA_CHAMP, HEAD);
    public static final Item gaia_champion_guard = new GaiaChampArmorItem(GaiaArmorMaterials.GAIA_CHAMP, CHEST);
    public static final Item gaia_champion_greaves = new GaiaChampArmorItem(GaiaArmorMaterials.GAIA_CHAMP, LEGS);
    public static final Item gaia_champion_boots = new GaiaChampArmorItem(GaiaArmorMaterials.GAIA_CHAMP, FEET);

    public static final Item agate_sword = new BasicGaiaSwordItem(GaiaToolMaterials.AGATE);
    public static final Item agate_pickaxe = new BasicGaiaPickaxeItem(GaiaToolMaterials.AGATE);
    public static final Item agate_axe = new BasicGaiaAxeItem(GaiaToolMaterials.AGATE);
    public static final Item agate_shovel = new BasicGaiaShovelItem(GaiaToolMaterials.AGATE);
    public static final Item sugilite_sword = new BasicGaiaSwordItem(GaiaToolMaterials.SUGILITE);
    public static final Item sugilite_pickaxe = new BasicGaiaPickaxeItem(GaiaToolMaterials.SUGILITE);
    public static final Item sugilite_axe = new BasicGaiaAxeItem(GaiaToolMaterials.SUGILITE);
    public static final Item sugilite_shovel = new BasicGaiaShovelItem(GaiaToolMaterials.SUGILITE);
    public static final Item ixiolite_sword = new BasicGaiaSwordItem(GaiaToolMaterials.IXIOLITE);
    public static final Item ixiolite_pickaxe = new BasicGaiaPickaxeItem(GaiaToolMaterials.IXIOLITE);
    public static final Item ixiolite_axe = new BasicGaiaAxeItem(GaiaToolMaterials.IXIOLITE);
    public static final Item ixiolite_shovel = new BasicGaiaShovelItem(GaiaToolMaterials.IXIOLITE);
    public static final Item euclase_sword = new BasicGaiaSwordItem(GaiaToolMaterials.EUCLASE);
    public static final Item euclase_pickaxe = new BasicGaiaPickaxeItem(GaiaToolMaterials.EUCLASE);
    public static final Item euclase_axe = new BasicGaiaAxeItem(GaiaToolMaterials.EUCLASE);
    public static final Item euclase_shovel = new BasicGaiaShovelItem(GaiaToolMaterials.EUCLASE);
    public static final Item carnelian_sword = new BasicGaiaSwordItem(GaiaToolMaterials.CARNELIAN);
    public static final Item carnelian_pickaxe = new BasicGaiaPickaxeItem(GaiaToolMaterials.CARNELIAN);
    public static final Item carnelian_axe = new BasicGaiaAxeItem(GaiaToolMaterials.CARNELIAN);
    public static final Item carnelian_shovel = new BasicGaiaShovelItem(GaiaToolMaterials.CARNELIAN);
    public static final Item benitoite_sword = new BasicGaiaSwordItem(GaiaToolMaterials.BENITOITE);
    public static final Item benitoite_pickaxe = new BasicGaiaPickaxeItem(GaiaToolMaterials.BENITOITE);
    public static final Item benitoite_axe = new BasicGaiaAxeItem(GaiaToolMaterials.BENITOITE);
    public static final Item benitoite_shovel = new BasicGaiaShovelItem(GaiaToolMaterials.BENITOITE);
    public static final Item chalcedony_sword = new BasicGaiaSwordItem(GaiaToolMaterials.CHALCEDONY);
    public static final Item chalcedony_pickaxe = new BasicGaiaPickaxeItem(GaiaToolMaterials.CHALCEDONY);
    public static final Item chalcedony_axe = new BasicGaiaAxeItem(GaiaToolMaterials.CHALCEDONY);
    public static final Item chalcedony_shovel = new BasicGaiaShovelItem(GaiaToolMaterials.CHALCEDONY);
    public static final Item agate_arrow = new AgateArrowItem();
    public static final Item old_bow = new OldBowItem();

    public static final Item malachite_guard_baton = new MalachiteGuardSwordItem(GaiaToolMaterials.MALACHITE);
    public static final Item apex_predator_mace = new ApexPredatorSwordItem(GaiaToolMaterials.TIGER_EYE);
    public static final Item spinel_princess_flamberge = new SpinelPrincessSwordItem(GaiaToolMaterials.SPINEL);
    public static final Item zircon_prince_razor = new ZirconPrinceSwordItem(GaiaToolMaterials.ZIRCON);
    public static final Item corrupt_warrior_sword = new CorruptWarriorSwordItem(GaiaToolMaterials.CORRUPT);
    public static final Item gaia_duchess_khopesh = new GaiaDuchessSwordItem(GaiaToolMaterials.BIXBITE);
    public static final Item gaia_baron_dagger = new GaiaBaronSwordItem(GaiaToolMaterials.TSAVORITE);
    public static final Item gaia_duke_blade = new GaiaDukeSwordItem(GaiaToolMaterials.LARVIKITE);
    public static final Item gaia_champion_sword = new GaiaChampSwordItem(GaiaToolMaterials.GAIA_CHAMP);

    public static ItemStack mineral_water_bucket_item;
    public static ItemStack superhot_magma_bucket_item;
    public static ItemStack sweet_muck_bucket_item;
    public static ItemStack liquid_bismuth_bucket_item;
    public static ItemStack liquid_aura_bucket_item;
}
